## this is read by the files:
## - awsim_fuzzingbroker_lidar.py
## - fuzzingbroker_camera.py

## Lidar
sensor:
  sensor_name: "Lidar"
  ros2_topic: "/sensing/lidar/top/pointcloud_raw_ex"
  sensor_type: 'lidar'

fuzzing_parameter_lidar:
  sensor: 
    sensor_name: "Lidar"
    ros2_topic: "/sensing/lidar/top/pointcloud_raw_ex"
    sensor_type: 'lidar'
  random_seed: 5
  amount: 0.1
  dispersion: 0.1
  location_x: 0.4
  location_y: 0.5
  distance: 30.0
  intensity: 0.1
  width: 100
  height: 60
  steps: 10.0

lidar_fuzzing_node:
  node_name: "lidar_fuzzing_node"
  topic_subscribe: "/sensing/lidar/top/pointcloud_raw_ex"
  topic_publish: "/sensing/lidar/top/pointcloud_raw_ex_fuzzed"
  fuzzing_parameter: "fuzzing_parameter_lidar"


## Camera
sensor:
  sensor_name: "Camera"
  ros2_topic: "/sensing/camera/traffic_light/image_raw"
  sensor_type: 'camera'

fuzzing_parameter_camera:
  sensor: 
    sensor_name: "camera"
    ros2_topic: "/sensing/camera/traffic_light/image_raw"
    sensor_type: 'camera'
  random_seed: 5
  amount: 0.1
  dispersion: 0.1
  location_x: 0.4
  location_y: 0.5
  distance: 30.0
  intensity: 0.1
  width: 100
  height: 60
  steps: 10.0

camera_fuzzing_node:
  node_name: "camera_fuzzing_node"
  topic_subscribe: "/sensing/camera/traffic_light/image_raw"
  topic_publish: "/sensing/camera/traffic_light/image_raw_fuzzed"
  fuzzing_parameter: "fuzzing_parameter_camera"

